;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Damage",DevComment="伤害Tag")
+GameplayTagList=(Tag="Damage.Enviroment.KillZ",DevComment="低于一定高度就杀死")
+GameplayTagList=(Tag="Damage.Enviroment.LowerObstacleHit",DevComment="低处障碍物撞击")
+GameplayTagList=(Tag="Damage.Enviroment.UpperObstacleHit",DevComment="高处障碍物撞击")
+GameplayTagList=(Tag="Skill",DevComment="SKills")
+GameplayTagList=(Tag="Skill.Defensive",DevComment="防御类技能")
+GameplayTagList=(Tag="Skill.Defensive.Shield",DevComment="单次护盾，抵挡一次伤害")
+GameplayTagList=(Tag="Skill.Movement",DevComment="运动类技能")
+GameplayTagList=(Tag="Skill.Movement.Dash",DevComment="冲刺")
+GameplayTagList=(Tag="Skill.Movement.Unstoppable",DevComment="无敌冲刺")

